version: "2"
services:
  auth-api:
    build:
      context: ./backend/auth-api/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mynetwork
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tcc
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  db:
    container_name: mysql
    image: mysql:8
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "root" # TODO: Change this
      MYSQL_DATABASE: tcc

    volumes:
      - my-datavolume:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  my-datavolume:

networks:
  mynetwork:
    driver: bridge
