name: challenges_repository
description: Repositório que irá cuidar da parte de desafios do flutter
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  intl: ^0.19.0
  user_repository:
    path: ../user_repository/
  authentication_repository:
    path: ../authentication_repository/
  storage_repository:
    path: ../storage_repository/

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0