name: user_repository
description: Repositório que cuida do domínio de usuário
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0